import io
import tokenize

# Example Python code
python_code = """
def नमस्ते_दुनिया():
    print("नमस्ते दुनिया!")

def जोड़(संख्या१, संख्या२):
    return संख्या१ + संख्या२

नमस्ते_दुनिया()
परिणाम = जोड़(५, ३)
print(f"जोड़ का परिणाम: {परिणाम}")
"""


# Use io.BytesIO to simulate a file-like object for the tokenizer
# The tokenize module expects bytes, so encode the string
source_text = io.StringIO(python_code)
token_list = []

# Iterate over the tokens generated by tokenize.generate_tokens
for token_info in tokenize.generate_tokens(source_text.readline):
    token_list.append(token_info)


# Create a new list to hold the modified tokens (or modify in place)
modified_tokens = []

for token in token_list:
    new_string = token.string
    
    # 1. Rename the function 'calculate' to 'compute'
    if token.type == tokenize.NAME:
        new_string = 'compute'

        
    # Recreate the token tuple using the original type and the (potentially) new string
    # untokenize requires (type, string) as the first two elements.
    modified_tokens.append((token.type, new_string))

reconstructed_code_string  = tokenize.untokenize(modified_tokens)
 

print("--- Original Code ---")
print(python_code)
print("\n--- Modified Code ---")
print(reconstructed_code_string)